"""
Portfolio companies — current Founders Capital holdings. Metadata used by
the /portfolio grid card (PortfolioCard) and the portfolio section on /.
"""

PORTFOLIO = [
    {
        "id": "bondora",
        "name": "Bondora",
        "url": "https://bondora.com",
        "url_label": "bondora.com",
        "sector": "FinTech",
        "tagline": "Consumer lending marketplace serving over 1.4M registered customers across the EU. Over €2B invested and €1.6B originated to date.",
        "tags": ["Consumer credit", "EU", "2007"],
        "logo": "/static/portfolio/bondora.svg",
        "initials": "BO",
    },
    {
        "id": "estateguru",
        "name": "EstateGuru",
        "url": "https://estateguru.co",
        "url_label": "estateguru.co",
        "sector": "FinTech",
        "tagline": "Pan-European property-bridge lending marketplace. €940M+ lent across 7,700+ property-backed loans, 159k+ investors, 8 countries.",
        "tags": ["Property finance", "EU", "2014"],
        "logo": "/static/portfolio/estateguru.svg",
        "initials": "EG",
    },
    {
        "id": "investly",
        "name": "Investly",
        "url": "https://investly.co",
        "url_label": "investly.co",
        "sector": "FinTech",
        "tagline": "SME invoice-finance marketplace — working-capital financing for European small businesses underwritten through open-banking data.",
        "tags": ["SME finance", "Invoice", "UK/EE"],
        "logo": "/static/portfolio/investly.svg",
        "initials": "IN",
    },
    {
        "id": "kanvas",
        "name": "Kanvas",
        "url": "https://kanvas.ai",
        "url_label": "kanvas.ai",
        "sector": "Alternative assets",
        "tagline": "AI-native research and portfolio-construction platform for alternative-asset managers — private credit, real estate, venture.",
        "tags": ["Alts", "AI", "Analytics"],
        "logo": "/static/portfolio/kanvas.svg",
        "initials": "KA",
    },
    {
        "id": "hedgefolio",
        "name": "Hedgefolio",
        "url": "https://hedgefolio.app",
        "url_label": "hedgefolio.app",
        "sector": "FinTech",
        "tagline": "Continuous hedge-fund monitoring and transparency layer for LPs and allocators — exposures, risk factors and drift, one dashboard.",
        "tags": ["Hedge funds", "Risk", "LP tooling"],
        "logo": "/static/portfolio/hedgefolio.svg",
        "initials": "HF",
    },
    {
        "id": "liquidround",
        "name": "LiquidRound",
        "url": "https://liquidround.com",
        "url_label": "liquidround.com",
        "sector": "Legal AI · M&A",
        "tagline": "AI-first M&A legal workflow — diligence, disclosure-schedule drafting and deal-lifecycle automation for European corporate-law practices.",
        "tags": ["Legal AI", "M&A", "Dual-use"],
        "logo": "/static/portfolio/liquidround.svg",
        "initials": "LR",
    },
    {
        "id": "tendly",
        "name": "Tendly",
        "url": "https://tendly.eu",
        "url_label": "tendly.eu",
        "sector": "Public procurement AI",
        "tagline": "AI-powered tender discovery, matching and bid-drafting for companies chasing government contracts across 10+ European markets.",
        "tags": ["GovTech", "Procurement", "AI agents"],
        "logo": "/static/portfolio/tendly.svg",
        "initials": "TY",
    },
    {
        "id": "foodangels",
        "name": "FoodAngels",
        "url": "https://foodangels.app",
        "url_label": "foodangels.app",
        "sector": "Sustainability",
        "tagline": "Consumer-facing platform tackling food surplus and food waste — connecting excess supply with households and community programmes.",
        "tags": ["ClimateTech", "Food", "Consumer"],
        "logo": "/static/portfolio/foodangels.svg",
        "initials": "FA",
    },
    {
        "id": "mentastic",
        "name": "Mentastic",
        "url": "https://mentastic.chat",
        "url_label": "mentastic.chat",
        "sector": "Mental wellness",
        "tagline": "Conversational AI for mental-wellness support — clinician-supervised, privacy-first, accessible across European languages.",
        "tags": ["DigitalHealth", "Conversational AI", "Wellness"],
        "logo": "/static/portfolio/mentastic.svg",
        "initials": "MC",
    },
]
